import mysql from 'mysql2/promise';

const DATABASE_URL = process.env.DATABASE_URL;

function mapDifficulty(d) {
  if (!d) return 'medium';
  const lower = d.toLowerCase();
  if (lower.includes('easy')) return 'easy';
  if (lower.includes('hard')) return 'hard';
  return 'medium';
}

const RECIPES = [
  // ═══ DESAYUNOS ═══════════════════════════════════════════════════════════════
  { name:"Porridge de avena con frutos rojos", description:"Gachas de avena cremosas con arándanos, frambuesas y semillas de chía. Alto en fibra y antioxidantes.", mealTime:"desayuno", category:"cereales", prepTime:5, cookTime:10, servings:1, difficulty:"easy", calories:320, protein:12, carbohydrates:52, fat:7, fiber:9, allergens:["gluten","lacteos"], tags:["alto_fibra","antioxidantes","sin_azucar"], ingredients:[{name:"Copos de avena",quantity:"60g"},{name:"Leche de avena",quantity:"250ml"},{name:"Arándanos",quantity:"50g"},{name:"Frambuesas",quantity:"30g"},{name:"Semillas de chía",quantity:"10g"},{name:"Canela",quantity:"1 pizca"}], instructions:["Calentar la leche de avena en un cazo a fuego medio.","Añadir los copos de avena y remover constantemente durante 5-7 minutos.","Retirar del fuego y dejar reposar 2 minutos.","Servir con los frutos rojos por encima y espolvorear las semillas de chía y la canela."] },
  { name:"Tostadas de aguacate con huevo pochado", description:"Pan integral tostado con aguacate machacado, huevo pochado y semillas de sésamo. Desayuno completo y nutritivo.", mealTime:"desayuno", category:"huevos", prepTime:10, cookTime:5, servings:1, difficulty:"medium", calories:380, protein:18, carbohydrates:32, fat:20, fiber:8, allergens:["gluten","huevos"], tags:["alto_proteina","grasas_saludables","sin_lacteos"], ingredients:[{name:"Pan integral",quantity:"2 rebanadas"},{name:"Aguacate maduro",quantity:"1/2 unidad"},{name:"Huevo",quantity:"1 unidad"},{name:"Limón",quantity:"unas gotas"},{name:"Semillas de sésamo",quantity:"5g"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Tostar el pan integral.","Machacar el aguacate con unas gotas de limón, sal y pimienta.","Calentar agua con un chorrito de vinagre y hacer el huevo pochado durante 3 minutos.","Extender el aguacate sobre las tostadas, colocar el huevo pochado encima y espolvorear las semillas de sésamo."] },
  { name:"Smoothie bowl de mango y espinacas", description:"Bowl de batido verde con mango, espinacas, plátano y toppings crujientes. Rico en vitaminas y minerales.", mealTime:"desayuno", category:"batidos", prepTime:10, cookTime:0, servings:1, difficulty:"easy", calories:290, protein:8, carbohydrates:55, fat:5, fiber:7, allergens:[], tags:["vegano","sin_gluten","vitaminas","verde"], ingredients:[{name:"Mango congelado",quantity:"150g"},{name:"Espinacas baby",quantity:"30g"},{name:"Plátano",quantity:"1/2 unidad"},{name:"Leche de coco",quantity:"100ml"},{name:"Granola sin azúcar",quantity:"20g"},{name:"Semillas de calabaza",quantity:"10g"},{name:"Kiwi",quantity:"1/2 unidad"}], instructions:["Triturar el mango congelado, espinacas, plátano y leche de coco hasta obtener una crema espesa.","Verter en un bowl.","Decorar con granola, semillas de calabaza y rodajas de kiwi."] },
  { name:"Tortilla de claras con verduras", description:"Tortilla ligera de claras de huevo con pimiento, cebolla y espinacas. Baja en calorías y alta en proteína.", mealTime:"desayuno", category:"huevos", prepTime:10, cookTime:8, servings:1, difficulty:"easy", calories:180, protein:22, carbohydrates:8, fat:5, fiber:3, allergens:["huevos"], tags:["alto_proteina","bajo_calorias","sin_lacteos","fitness"], ingredients:[{name:"Claras de huevo",quantity:"4 unidades"},{name:"Pimiento rojo",quantity:"50g"},{name:"Cebolla",quantity:"30g"},{name:"Espinacas",quantity:"30g"},{name:"Aceite de oliva",quantity:"5ml"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Picar el pimiento y la cebolla en trozos pequeños.","Saltear las verduras en una sartén con aceite durante 3 minutos.","Añadir las espinacas y cocinar 1 minuto más.","Batir las claras con sal y pimienta, verter sobre las verduras.","Cocinar a fuego medio-bajo hasta que cuaje, doblar por la mitad y servir."] },
  { name:"Yogur griego con nueces y miel", description:"Yogur griego natural con nueces, miel de abeja y canela. Desayuno proteico y saciante.", mealTime:"desayuno", category:"lacteos", prepTime:3, cookTime:0, servings:1, difficulty:"easy", calories:260, protein:15, carbohydrates:22, fat:12, fiber:1, allergens:["lacteos","frutos_secos"], tags:["alto_proteina","probioticos","rapido"], ingredients:[{name:"Yogur griego 0%",quantity:"200g"},{name:"Nueces",quantity:"20g"},{name:"Miel",quantity:"10g"},{name:"Canela",quantity:"1 pizca"}], instructions:["Verter el yogur griego en un bol.","Añadir las nueces troceadas por encima.","Rociar con la miel y espolvorear la canela."] },
  { name:"Pancakes de plátano y avena", description:"Tortitas saludables sin harina con plátano maduro y avena. Sin azúcar añadido.", mealTime:"desayuno", category:"cereales", prepTime:5, cookTime:10, servings:2, difficulty:"easy", calories:240, protein:10, carbohydrates:44, fat:4, fiber:5, allergens:["gluten","huevos"], tags:["sin_azucar","alto_fibra","vegetal"], ingredients:[{name:"Plátano maduro",quantity:"2 unidades"},{name:"Copos de avena",quantity:"80g"},{name:"Huevo",quantity:"1 unidad"},{name:"Canela",quantity:"1 cucharadita"},{name:"Aceite de coco",quantity:"5ml"}], instructions:["Triturar el plátano con un tenedor hasta obtener un puré.","Mezclar con los copos de avena, el huevo y la canela.","Calentar una sartén antiadherente con aceite de coco.","Verter pequeñas porciones y cocinar 2-3 minutos por cada lado hasta dorar."] },
  { name:"Bol de frutas con semillas y granola", description:"Combinación de frutas de temporada con granola casera y semillas de lino. Desayuno energético.", mealTime:"desayuno", category:"frutas", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:280, protein:7, carbohydrates:52, fat:8, fiber:8, allergens:["frutos_secos","gluten"], tags:["vegano","antioxidantes","fibra"], ingredients:[{name:"Fresas",quantity:"80g"},{name:"Plátano",quantity:"1 unidad"},{name:"Kiwi",quantity:"1 unidad"},{name:"Granola sin azúcar",quantity:"30g"},{name:"Semillas de lino",quantity:"10g"},{name:"Zumo de naranja",quantity:"50ml"}], instructions:["Cortar todas las frutas en trozos medianos.","Colocar en un bol y rociar con el zumo de naranja.","Añadir la granola y las semillas de lino por encima."] },
  { name:"Batido proteico de fresa y vainilla", description:"Batido post-entreno con fresas, proteína de vainilla, leche de almendras y plátano.", mealTime:"desayuno", category:"batidos", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:310, protein:28, carbohydrates:38, fat:5, fiber:4, allergens:["lacteos","frutos_secos"], tags:["alto_proteina","post_entreno","fitness"], ingredients:[{name:"Fresas congeladas",quantity:"150g"},{name:"Proteína de vainilla",quantity:"30g"},{name:"Leche de almendras",quantity:"200ml"},{name:"Plátano",quantity:"1/2 unidad"},{name:"Hielo",quantity:"4 cubitos"}], instructions:["Añadir todos los ingredientes a la batidora.","Triturar hasta obtener una textura cremosa y sin grumos.","Servir inmediatamente."] },
  { name:"Tostada de queso cottage con tomate", description:"Pan de centeno tostado con queso cottage, tomate cherry y orégano. Bajo en grasa y alto en proteína.", mealTime:"desayuno", category:"lacteos", prepTime:5, cookTime:3, servings:1, difficulty:"easy", calories:220, protein:16, carbohydrates:28, fat:4, fiber:4, allergens:["gluten","lacteos"], tags:["bajo_grasa","alto_proteina","rapido"], ingredients:[{name:"Pan de centeno",quantity:"2 rebanadas"},{name:"Queso cottage",quantity:"100g"},{name:"Tomate cherry",quantity:"6 unidades"},{name:"Orégano",quantity:"1 pizca"},{name:"Aceite de oliva virgen",quantity:"5ml"}], instructions:["Tostar el pan de centeno.","Extender el queso cottage sobre las tostadas.","Cortar los tomates cherry por la mitad y colocar encima.","Rociar con aceite de oliva y espolvorear orégano."] },
  { name:"Muesli con leche vegetal y fruta", description:"Muesli suizo con leche de avena, manzana rallada y pasas. Remojado toda la noche para mayor digestibilidad.", mealTime:"desayuno", category:"cereales", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:350, protein:9, carbohydrates:62, fat:7, fiber:8, allergens:["gluten","frutos_secos"], tags:["fibra","vegetal","overnight"], ingredients:[{name:"Muesli sin azúcar",quantity:"60g"},{name:"Leche de avena",quantity:"150ml"},{name:"Manzana",quantity:"1/2 unidad"},{name:"Pasas",quantity:"15g"},{name:"Almendras laminadas",quantity:"10g"}], instructions:["La noche anterior, mezclar el muesli con la leche de avena en un bol.","Tapar y refrigerar toda la noche.","Por la mañana, rallar la manzana y añadir junto con las pasas y almendras."] },
  { name:"Bol de açaí con granola y coco", description:"Bowl de açaí con granola, coco rallado, plátano y semillas de chía. Energético y antioxidante.", mealTime:"desayuno", category:"batidos", prepTime:10, cookTime:0, servings:1, difficulty:"easy", calories:380, protein:8, carbohydrates:58, fat:14, fiber:10, allergens:["frutos_secos","gluten"], tags:["vegano","antioxidantes","superfood","energia"], ingredients:[{name:"Pulpa de açaí congelada",quantity:"100g"},{name:"Plátano congelado",quantity:"1 unidad"},{name:"Leche de almendras",quantity:"80ml"},{name:"Granola sin azúcar",quantity:"30g"},{name:"Coco rallado",quantity:"10g"},{name:"Semillas de chía",quantity:"10g"}], instructions:["Triturar el açaí con el plátano congelado y la leche de almendras.","Verter en un bowl.","Decorar con granola, coco rallado y semillas de chía."] },
  { name:"Tortitas proteicas de avena y claras", description:"Pancakes proteicos con claras de huevo, avena y proteína en polvo. Perfectas post-entreno.", mealTime:"desayuno", category:"fitness", prepTime:5, cookTime:10, servings:1, difficulty:"easy", calories:350, protein:32, carbohydrates:40, fat:5, fiber:5, allergens:["gluten","huevos"], tags:["alto_proteina","post_entreno","fitness","sin_azucar"], ingredients:[{name:"Claras de huevo",quantity:"4 unidades"},{name:"Copos de avena",quantity:"60g"},{name:"Proteína de vainilla",quantity:"20g"},{name:"Canela",quantity:"1 cucharadita"},{name:"Aceite de coco",quantity:"5ml"}], instructions:["Mezclar las claras, avena, proteína y canela hasta obtener una masa.","Calentar la sartén con aceite de coco.","Verter pequeñas porciones y cocinar 2-3 minutos por cada lado.","Servir con fruta fresca o miel."] },
  { name:"Overnight oats de chía y coco", description:"Avena remojada con leche de coco, semillas de chía y mango. Preparada la noche anterior.", mealTime:"desayuno", category:"cereales", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:340, protein:10, carbohydrates:54, fat:10, fiber:10, allergens:["gluten"], tags:["vegano","fibra","overnight","sin_azucar"], ingredients:[{name:"Copos de avena",quantity:"50g"},{name:"Leche de coco",quantity:"200ml"},{name:"Semillas de chía",quantity:"15g"},{name:"Mango",quantity:"80g"},{name:"Miel",quantity:"5g"}], instructions:["Mezclar la avena, chía y leche de coco en un bote.","Añadir la miel y remover bien.","Refrigerar toda la noche.","Por la mañana, añadir el mango troceado por encima."] },
  { name:"Huevos revueltos con salmón ahumado", description:"Huevos revueltos cremosos con salmón ahumado, cebollino y alcaparras. Desayuno lujoso y nutritivo.", mealTime:"desayuno", category:"huevos", prepTime:5, cookTime:5, servings:1, difficulty:"easy", calories:320, protein:28, carbohydrates:4, fat:20, fiber:0, allergens:["huevos","pescado"], tags:["alto_proteina","omega3","keto","bajo_carbohidratos"], ingredients:[{name:"Huevos",quantity:"3 unidades"},{name:"Salmón ahumado",quantity:"60g"},{name:"Cebollino",quantity:"5g"},{name:"Alcaparras",quantity:"10g"},{name:"Mantequilla",quantity:"5g"}], instructions:["Batir los huevos con sal y pimienta.","Cocinar a fuego muy bajo con la mantequilla, removiendo constantemente.","Retirar antes de que cuajen del todo.","Servir con el salmón ahumado, alcaparras y cebollino."] },
  { name:"Granola casera sin azúcar", description:"Granola horneada con avena, semillas, frutos secos y aceite de coco. Sin azúcar refinado.", mealTime:"desayuno", category:"cereales", prepTime:10, cookTime:25, servings:8, difficulty:"easy", calories:280, protein:8, carbohydrates:34, fat:14, fiber:5, allergens:["gluten","frutos_secos"], tags:["sin_azucar","fibra","horneado","meal_prep"], ingredients:[{name:"Copos de avena",quantity:"300g"},{name:"Almendras",quantity:"80g"},{name:"Semillas de girasol",quantity:"50g"},{name:"Aceite de coco",quantity:"40ml"},{name:"Miel",quantity:"30g"},{name:"Canela",quantity:"2 cucharaditas"},{name:"Vainilla",quantity:"1 cucharadita"}], instructions:["Precalentar el horno a 160°C.","Mezclar todos los ingredientes.","Extender en bandeja y hornear 20-25 minutos removiendo a mitad.","Dejar enfriar completamente antes de guardar."] },

  // ═══ MEDIA MAÑANA ════════════════════════════════════════════════════════════
  { name:"Manzana con mantequilla de almendras", description:"Snack saciante de manzana con mantequilla de almendras natural. Equilibrio perfecto de carbohidratos y grasas saludables.", mealTime:"media_manana", category:"snacks", prepTime:2, cookTime:0, servings:1, difficulty:"easy", calories:200, protein:5, carbohydrates:28, fat:9, fiber:4, allergens:["frutos_secos"], tags:["snack","grasas_saludables","sin_gluten"], ingredients:[{name:"Manzana",quantity:"1 unidad"},{name:"Mantequilla de almendras",quantity:"20g"}], instructions:["Lavar y cortar la manzana en gajos.","Servir con la mantequilla de almendras para mojar."] },
  { name:"Hummus con bastones de verduras", description:"Hummus casero con bastones de zanahoria, pepino y apio. Snack saludable rico en proteína vegetal.", mealTime:"media_manana", category:"snacks", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:180, protein:7, carbohydrates:22, fat:8, fiber:6, allergens:["sesamo"], tags:["vegano","sin_gluten","proteina_vegetal"], ingredients:[{name:"Garbanzos cocidos",quantity:"150g"},{name:"Tahini",quantity:"20g"},{name:"Limón",quantity:"1/2 unidad"},{name:"Ajo",quantity:"1 diente"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Zanahoria",quantity:"1 unidad"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Apio",quantity:"2 tallos"}], instructions:["Triturar los garbanzos con el tahini, zumo de limón, ajo y aceite hasta obtener una pasta suave.","Cortar las verduras en bastones.","Servir el hummus con los bastones de verduras."] },
  { name:"Kéfir con frutos del bosque", description:"Kéfir natural con mezcla de frutos del bosque. Probiótico natural que mejora la digestión.", mealTime:"media_manana", category:"lacteos", prepTime:2, cookTime:0, servings:1, difficulty:"easy", calories:140, protein:8, carbohydrates:18, fat:3, fiber:2, allergens:["lacteos"], tags:["probiotico","digestivo","bajo_calorias"], ingredients:[{name:"Kéfir natural",quantity:"200ml"},{name:"Frutos del bosque mixtos",quantity:"80g"}], instructions:["Verter el kéfir en un vaso.","Añadir los frutos del bosque por encima o mezclar."] },
  { name:"Edamame con sal marina", description:"Vainas de edamame cocidas al vapor con sal marina. Snack proteico de origen japonés.", mealTime:"media_manana", category:"legumbres", prepTime:2, cookTime:5, servings:1, difficulty:"easy", calories:120, protein:11, carbohydrates:10, fat:5, fiber:4, allergens:["soja"], tags:["vegano","alto_proteina","sin_gluten"], ingredients:[{name:"Edamame congelado",quantity:"150g"},{name:"Sal marina",quantity:"1 pizca"}], instructions:["Cocer el edamame al vapor o en agua hirviendo durante 5 minutos.","Escurrir y espolvorear con sal marina."] },
  { name:"Galletas de arroz con aguacate", description:"Tortas de arroz inflado con aguacate machacado y semillas de cáñamo. Snack ligero y nutritivo.", mealTime:"media_manana", category:"snacks", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:160, protein:4, carbohydrates:20, fat:8, fiber:4, allergens:[], tags:["sin_gluten","vegano","grasas_saludables"], ingredients:[{name:"Tortas de arroz",quantity:"3 unidades"},{name:"Aguacate",quantity:"1/4 unidad"},{name:"Semillas de cáñamo",quantity:"5g"},{name:"Sal y limón",quantity:"al gusto"}], instructions:["Machacar el aguacate con sal y unas gotas de limón.","Extender sobre las tortas de arroz.","Espolvorear las semillas de cáñamo."] },
  { name:"Huevos rellenos con atún y aguacate", description:"Huevos duros rellenos con mezcla de atún, aguacate y mostaza. Snack o entrante proteico.", mealTime:"media_manana", category:"huevos", prepTime:15, cookTime:10, servings:2, difficulty:"medium", calories:220, protein:18, carbohydrates:4, fat:14, fiber:2, allergens:["huevos","pescado"], tags:["alto_proteina","sin_gluten","keto","snack"], ingredients:[{name:"Huevos",quantity:"4 unidades"},{name:"Atún al natural",quantity:"80g"},{name:"Aguacate",quantity:"1/4 unidad"},{name:"Mostaza de Dijon",quantity:"5g"},{name:"Limón",quantity:"unas gotas"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Cocer los huevos 10 minutos, enfriar y pelar.","Cortar por la mitad y extraer las yemas.","Mezclar las yemas con el atún, aguacate, mostaza y limón.","Rellenar las claras con la mezcla.","Decorar con pimentón o perejil."] },
  { name:"Crema de cacahuete con manzana y apio", description:"Snack saciante de crema de cacahuete natural con bastones de manzana y apio.", mealTime:"media_manana", category:"snacks", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:230, protein:7, carbohydrates:24, fat:13, fiber:4, allergens:["cacahuetes"], tags:["vegano","sin_gluten","grasas_saludables","snack"], ingredients:[{name:"Crema de cacahuete natural",quantity:"25g"},{name:"Manzana",quantity:"1 unidad"},{name:"Apio",quantity:"2 tallos"}], instructions:["Cortar la manzana en gajos y el apio en bastones.","Servir con la crema de cacahuete para mojar."] },
  { name:"Frutos secos y fruta seca mixta", description:"Mix de nueces, almendras, pistachos y arándanos secos. Snack energético y nutritivo.", mealTime:"media_manana", category:"snacks", prepTime:1, cookTime:0, servings:1, difficulty:"easy", calories:220, protein:6, carbohydrates:18, fat:15, fiber:3, allergens:["frutos_secos"], tags:["vegano","sin_gluten","grasas_saludables","energia"], ingredients:[{name:"Nueces",quantity:"10g"},{name:"Almendras",quantity:"10g"},{name:"Pistachos",quantity:"10g"},{name:"Arándanos secos",quantity:"15g"}], instructions:["Mezclar todos los ingredientes en un bol pequeño.","Servir como snack."] },

  // ═══ COMIDAS ══════════════════════════════════════════════════════════════════
  { name:"Ensalada de pollo a la plancha con quinoa", description:"Ensalada completa con pollo a la plancha, quinoa, espinacas, tomate cherry y vinagreta de limón.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:20, servings:2, difficulty:"easy", calories:420, protein:38, carbohydrates:35, fat:12, fiber:6, allergens:[], tags:["alto_proteina","sin_gluten","fitness","bajo_grasa"], ingredients:[{name:"Pechuga de pollo",quantity:"300g"},{name:"Quinoa",quantity:"100g"},{name:"Espinacas baby",quantity:"80g"},{name:"Tomate cherry",quantity:"100g"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Limón",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Cocer la quinoa en agua con sal durante 15 minutos. Escurrir y enfriar.","Sazonar el pollo y cocinarlo a la plancha 5-6 minutos por cada lado.","Dejar reposar el pollo y cortar en tiras.","Mezclar las espinacas, tomate cherry cortado y pepino en rodajas.","Añadir la quinoa y el pollo.","Aliñar con zumo de limón, aceite de oliva, sal y pimienta."] },
  { name:"Salmón al horno con verduras asadas", description:"Lomo de salmón al horno con brócoli, zanahoria y pimiento asados. Rico en omega-3 y vitaminas.", mealTime:"comida", category:"pescados", prepTime:10, cookTime:25, servings:2, difficulty:"easy", calories:480, protein:42, carbohydrates:20, fat:24, fiber:7, allergens:["pescado"], tags:["omega3","sin_gluten","antiinflamatorio"], ingredients:[{name:"Lomo de salmón",quantity:"400g"},{name:"Brócoli",quantity:"200g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Pimiento rojo",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Ajo en polvo",quantity:"1 cucharadita"},{name:"Limón",quantity:"1 unidad"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Precalentar el horno a 200°C.","Cortar las verduras en trozos medianos y colocar en una bandeja con aceite, sal y pimienta.","Hornear las verduras 15 minutos.","Sazonar el salmón con ajo en polvo, sal, pimienta y zumo de limón.","Colocar el salmón sobre las verduras y hornear 10-12 minutos más.","Servir con rodajas de limón."] },
  { name:"Lentejas estofadas con verduras", description:"Estofado de lentejas con zanahoria, apio, tomate y especias. Plato completo rico en proteína vegetal y hierro.", mealTime:"comida", category:"legumbres", prepTime:15, cookTime:35, servings:4, difficulty:"medium", calories:360, protein:20, carbohydrates:55, fat:6, fiber:16, allergens:[], tags:["vegano","alto_hierro","fibra","economico"], ingredients:[{name:"Lentejas pardinas",quantity:"300g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Apio",quantity:"2 tallos"},{name:"Tomate triturado",quantity:"200g"},{name:"Cebolla",quantity:"1 unidad"},{name:"Ajo",quantity:"3 dientes"},{name:"Comino",quantity:"1 cucharadita"},{name:"Pimentón dulce",quantity:"1 cucharadita"},{name:"Aceite de oliva",quantity:"20ml"}], instructions:["Remojar las lentejas 30 minutos si son secas.","Sofreír la cebolla y el ajo picados en aceite durante 5 minutos.","Añadir la zanahoria y el apio en dados y cocinar 3 minutos.","Incorporar el tomate triturado, el comino y el pimentón.","Añadir las lentejas y cubrir con agua. Cocinar 25-30 minutos.","Rectificar de sal y servir."] },
  { name:"Pechuga de pavo con boniato y judías verdes", description:"Pechuga de pavo a la plancha con boniato asado y judías verdes al vapor. Menú de dieta completo.", mealTime:"comida", category:"carnes", prepTime:10, cookTime:30, servings:2, difficulty:"easy", calories:440, protein:45, carbohydrates:42, fat:8, fiber:9, allergens:[], tags:["alto_proteina","sin_gluten","dieta","fitness"], ingredients:[{name:"Pechuga de pavo",quantity:"400g"},{name:"Boniato",quantity:"300g"},{name:"Judías verdes",quantity:"200g"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Romero",quantity:"1 ramita"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Precalentar el horno a 200°C.","Pelar y cortar el boniato en cubos, aliñar con aceite, sal y romero. Hornear 25 minutos.","Cocer las judías verdes al vapor durante 8 minutos.","Sazonar el pavo y cocinarlo a la plancha 5-6 minutos por cada lado.","Servir todo junto en el plato."] },
  { name:"Ensalada de garbanzos mediterránea", description:"Ensalada fría de garbanzos con tomate, pepino, cebolla roja, aceitunas y queso feta. Mediterránea y saciante.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:0, servings:2, difficulty:"easy", calories:380, protein:16, carbohydrates:42, fat:16, fiber:12, allergens:["lacteos"], tags:["vegetariano","sin_gluten","mediterraneo","fibra"], ingredients:[{name:"Garbanzos cocidos",quantity:"300g"},{name:"Tomate",quantity:"2 unidades"},{name:"Pepino",quantity:"1 unidad"},{name:"Cebolla roja",quantity:"1/2 unidad"},{name:"Aceitunas negras",quantity:"50g"},{name:"Queso feta",quantity:"80g"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Orégano",quantity:"1 cucharadita"},{name:"Vinagre de vino",quantity:"10ml"}], instructions:["Escurrir y enjuagar los garbanzos.","Cortar el tomate, pepino y cebolla en dados.","Mezclar todos los ingredientes en un bol.","Aliñar con aceite, vinagre, orégano, sal y pimienta.","Desmigar el queso feta por encima y servir."] },
  { name:"Crema de calabaza y jengibre", description:"Sopa crema de calabaza con jengibre fresco, leche de coco y cúrcuma. Antiinflamatoria y reconfortante.", mealTime:"comida", category:"sopas", prepTime:15, cookTime:30, servings:4, difficulty:"easy", calories:180, protein:4, carbohydrates:28, fat:7, fiber:5, allergens:[], tags:["vegano","antiinflamatorio","sin_gluten","invierno"], ingredients:[{name:"Calabaza",quantity:"800g"},{name:"Jengibre fresco",quantity:"20g"},{name:"Leche de coco",quantity:"200ml"},{name:"Cúrcuma",quantity:"1 cucharadita"},{name:"Cebolla",quantity:"1 unidad"},{name:"Caldo de verduras",quantity:"600ml"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Pelar y cortar la calabaza en cubos.","Sofreír la cebolla y el jengibre rallado en aceite durante 5 minutos.","Añadir la calabaza, cúrcuma y caldo. Cocinar 20 minutos.","Triturar hasta obtener una crema suave.","Incorporar la leche de coco, calentar y rectificar de sal."] },
  { name:"Merluza al vapor con verduras", description:"Merluza al vapor con brócoli, zanahoria y guisantes. Plato ligero, digestivo y rico en proteína.", mealTime:"comida", category:"pescados", prepTime:10, cookTime:15, servings:2, difficulty:"easy", calories:280, protein:36, carbohydrates:18, fat:6, fiber:6, allergens:["pescado"], tags:["bajo_calorias","sin_gluten","digestivo","dieta"], ingredients:[{name:"Merluza en filetes",quantity:"400g"},{name:"Brócoli",quantity:"200g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Guisantes",quantity:"100g"},{name:"Limón",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Sal y hierbas",quantity:"al gusto"}], instructions:["Colocar la merluza en la vaporera con sal y rodajas de limón.","Añadir las verduras alrededor.","Cocer al vapor 12-15 minutos.","Servir con un chorrito de aceite de oliva."] },
  { name:"Pollo al curry con arroz integral", description:"Pollo en salsa de curry con leche de coco, servido con arroz integral. Plato completo y aromático.", mealTime:"comida", category:"carnes", prepTime:15, cookTime:30, servings:3, difficulty:"medium", calories:520, protein:40, carbohydrates:52, fat:14, fiber:4, allergens:[], tags:["sin_gluten","proteina","especiado"], ingredients:[{name:"Pechuga de pollo",quantity:"500g"},{name:"Arroz integral",quantity:"200g"},{name:"Leche de coco",quantity:"200ml"},{name:"Curry en polvo",quantity:"2 cucharaditas"},{name:"Cebolla",quantity:"1 unidad"},{name:"Tomate triturado",quantity:"150g"},{name:"Ajo",quantity:"2 dientes"},{name:"Jengibre",quantity:"10g"}], instructions:["Cocer el arroz integral según las instrucciones del paquete.","Cortar el pollo en dados y dorar en una sartén.","Sofreír la cebolla, ajo y jengibre. Añadir el curry y cocinar 1 minuto.","Incorporar el tomate y la leche de coco. Cocinar 15 minutos.","Añadir el pollo y cocinar 10 minutos más.","Servir sobre el arroz integral."] },
  { name:"Ensalada de atún con huevo y espárragos", description:"Ensalada Niçoise adaptada con atún al natural, huevo cocido, espárragos y judías verdes.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:10, servings:2, difficulty:"easy", calories:360, protein:32, carbohydrates:18, fat:16, fiber:5, allergens:["pescado","huevos"], tags:["alto_proteina","sin_gluten","mediterraneo"], ingredients:[{name:"Atún al natural",quantity:"200g"},{name:"Huevos",quantity:"2 unidades"},{name:"Espárragos verdes",quantity:"150g"},{name:"Judías verdes",quantity:"150g"},{name:"Tomate cherry",quantity:"100g"},{name:"Aceitunas negras",quantity:"40g"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Mostaza de Dijon",quantity:"5g"},{name:"Vinagre de manzana",quantity:"10ml"}], instructions:["Cocer los huevos 10 minutos, enfriar y pelar.","Blanquear los espárragos y judías verdes 3-4 minutos.","Preparar la vinagreta mezclando aceite, vinagre y mostaza.","Montar la ensalada con todos los ingredientes.","Aliñar y servir."] },
  { name:"Gazpacho andaluz", description:"Sopa fría de tomate, pepino, pimiento y ajo. Refrescante, bajo en calorías y lleno de vitaminas.", mealTime:"comida", category:"sopas", prepTime:15, cookTime:0, servings:4, difficulty:"easy", calories:120, protein:3, carbohydrates:16, fat:5, fiber:4, allergens:[], tags:["vegano","sin_gluten","bajo_calorias","verano","crudo"], ingredients:[{name:"Tomates maduros",quantity:"800g"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Pimiento verde",quantity:"1/2 unidad"},{name:"Ajo",quantity:"1 diente"},{name:"Aceite de oliva virgen extra",quantity:"40ml"},{name:"Vinagre de jerez",quantity:"15ml"},{name:"Sal",quantity:"al gusto"},{name:"Pan duro",quantity:"30g"}], instructions:["Remojar el pan en agua fría 10 minutos.","Triturar todos los ingredientes hasta obtener una crema fina.","Pasar por un colador para eliminar pieles y semillas.","Refrigerar al menos 2 horas antes de servir.","Servir frío con guarnición de pepino y pimiento picados."] },
  { name:"Wok de tofu con verduras y soja", description:"Tofu firme salteado con brócoli, zanahoria, pimiento y salsa de soja baja en sodio. Plato vegano y proteico.", mealTime:"comida", category:"vegetariano", prepTime:15, cookTime:15, servings:2, difficulty:"medium", calories:320, protein:18, carbohydrates:28, fat:14, fiber:8, allergens:["soja"], tags:["vegano","sin_gluten","proteina_vegetal","asiatico"], ingredients:[{name:"Tofu firme",quantity:"300g"},{name:"Brócoli",quantity:"200g"},{name:"Zanahoria",quantity:"1 unidad"},{name:"Pimiento rojo",quantity:"1 unidad"},{name:"Salsa de soja baja en sodio",quantity:"30ml"},{name:"Aceite de sésamo",quantity:"10ml"},{name:"Ajo",quantity:"2 dientes"},{name:"Jengibre",quantity:"10g"},{name:"Semillas de sésamo",quantity:"10g"}], instructions:["Cortar el tofu en dados y presionar para eliminar el exceso de agua.","Dorar el tofu en aceite de sésamo hasta que esté crujiente. Reservar.","En el mismo wok, saltear el ajo y jengibre picados.","Añadir las verduras cortadas y saltear a fuego alto 5 minutos.","Incorporar el tofu y la salsa de soja. Mezclar bien.","Servir con semillas de sésamo por encima."] },
  { name:"Bacalao al horno con tomate y aceitunas", description:"Lomo de bacalao al horno sobre cama de tomate, aceitunas y cebolla. Plato mediterráneo bajo en grasa.", mealTime:"comida", category:"pescados", prepTime:10, cookTime:20, servings:2, difficulty:"easy", calories:310, protein:38, carbohydrates:12, fat:10, fiber:3, allergens:["pescado"], tags:["bajo_grasa","sin_gluten","mediterraneo","proteina"], ingredients:[{name:"Lomo de bacalao",quantity:"400g"},{name:"Tomate triturado",quantity:"200g"},{name:"Aceitunas verdes",quantity:"50g"},{name:"Cebolla",quantity:"1 unidad"},{name:"Ajo",quantity:"2 dientes"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Perejil",quantity:"al gusto"}], instructions:["Precalentar el horno a 190°C.","Sofreír la cebolla y el ajo en aceite. Añadir el tomate y cocinar 5 minutos.","Extender la salsa en una fuente de horno.","Colocar el bacalao encima y distribuir las aceitunas.","Hornear 15-18 minutos.","Espolvorear perejil fresco y servir."] },
  { name:"Pasta integral con pesto de espinacas", description:"Pasta integral con pesto casero de espinacas, albahaca, piñones y parmesano. Nutritiva y sabrosa.", mealTime:"comida", category:"pasta", prepTime:15, cookTime:12, servings:2, difficulty:"easy", calories:480, protein:18, carbohydrates:68, fat:16, fiber:9, allergens:["gluten","lacteos","frutos_secos"], tags:["vegetariano","fibra","italiano"], ingredients:[{name:"Pasta integral",quantity:"200g"},{name:"Espinacas baby",quantity:"100g"},{name:"Albahaca fresca",quantity:"20g"},{name:"Piñones",quantity:"30g"},{name:"Parmesano rallado",quantity:"40g"},{name:"Aceite de oliva",quantity:"40ml"},{name:"Ajo",quantity:"1 diente"},{name:"Sal",quantity:"al gusto"}], instructions:["Cocer la pasta integral al dente según las instrucciones.","Triturar las espinacas, albahaca, piñones, parmesano, ajo y aceite hasta obtener el pesto.","Mezclar la pasta caliente con el pesto.","Servir con más parmesano rallado."] },
  { name:"Sopa minestrone de verduras", description:"Sopa italiana de verduras con pasta integral, judías blancas y tomate. Reconfortante y nutritiva.", mealTime:"comida", category:"sopas", prepTime:20, cookTime:35, servings:4, difficulty:"medium", calories:280, protein:12, carbohydrates:45, fat:6, fiber:10, allergens:["gluten"], tags:["vegetariano","fibra","italiano","invierno"], ingredients:[{name:"Judías blancas cocidas",quantity:"200g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Apio",quantity:"2 tallos"},{name:"Calabacín",quantity:"1 unidad"},{name:"Tomate triturado",quantity:"200g"},{name:"Pasta integral pequeña",quantity:"80g"},{name:"Caldo de verduras",quantity:"1.2L"},{name:"Ajo",quantity:"2 dientes"},{name:"Albahaca",quantity:"al gusto"}], instructions:["Sofreír el ajo, zanahoria y apio en aceite durante 5 minutos.","Añadir el calabacín y el tomate. Cocinar 5 minutos.","Incorporar el caldo y las judías. Hervir 15 minutos.","Añadir la pasta y cocinar hasta que esté al dente.","Servir con albahaca fresca."] },
  { name:"Pollo al limón con espárragos", description:"Pechuga de pollo marinada en limón y hierbas, servida con espárragos a la plancha.", mealTime:"comida", category:"carnes", prepTime:20, cookTime:20, servings:2, difficulty:"easy", calories:350, protein:42, carbohydrates:8, fat:14, fiber:4, allergens:[], tags:["alto_proteina","sin_gluten","bajo_carbohidratos","fitness"], ingredients:[{name:"Pechuga de pollo",quantity:"400g"},{name:"Espárragos verdes",quantity:"300g"},{name:"Limón",quantity:"2 unidades"},{name:"Ajo",quantity:"3 dientes"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Tomillo",quantity:"1 cucharadita"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Marinar el pollo con zumo de limón, ajo picado, tomillo, aceite, sal y pimienta durante 15 minutos.","Cocinarlo a la plancha 6-7 minutos por cada lado.","Asar los espárragos en la misma plancha con un poco de aceite y sal.","Servir el pollo con los espárragos y rodajas de limón."] },
  { name:"Buddha bowl de garbanzos crujientes", description:"Bowl completo con garbanzos especiados al horno, arroz integral, aguacate, zanahoria rallada y tahini.", mealTime:"comida", category:"bowls", prepTime:20, cookTime:30, servings:2, difficulty:"medium", calories:520, protein:20, carbohydrates:62, fat:22, fiber:14, allergens:["sesamo"], tags:["vegano","sin_gluten","fibra","completo"], ingredients:[{name:"Garbanzos cocidos",quantity:"300g"},{name:"Arroz integral",quantity:"150g"},{name:"Aguacate",quantity:"1 unidad"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Espinacas baby",quantity:"60g"},{name:"Tahini",quantity:"30g"},{name:"Limón",quantity:"1 unidad"},{name:"Pimentón",quantity:"1 cucharadita"},{name:"Comino",quantity:"1 cucharadita"}], instructions:["Precalentar el horno a 200°C.","Mezclar los garbanzos con pimentón, comino, aceite y sal. Hornear 25-30 minutos.","Cocer el arroz integral.","Rallar la zanahoria y cortar el aguacate en láminas.","Preparar la salsa de tahini con limón, agua y sal.","Montar el bowl con todos los ingredientes y rociar con la salsa."] },
  { name:"Dorada a la sal", description:"Dorada entera cocinada en costra de sal. Técnica que preserva todos los jugos y nutrientes del pescado.", mealTime:"comida", category:"pescados", prepTime:10, cookTime:35, servings:2, difficulty:"medium", calories:320, protein:44, carbohydrates:0, fat:14, fiber:0, allergens:["pescado"], tags:["sin_gluten","sin_carbohidratos","proteina","especial"], ingredients:[{name:"Dorada entera",quantity:"600g"},{name:"Sal gruesa",quantity:"1kg"},{name:"Limón",quantity:"1 unidad"},{name:"Hierbas aromáticas",quantity:"al gusto"}], instructions:["Precalentar el horno a 200°C.","Rellenar el interior de la dorada con rodajas de limón y hierbas.","Cubrir completamente con sal gruesa en una fuente.","Hornear 30-35 minutos.","Romper la costra de sal y servir la dorada limpia."] },
  { name:"Ensalada de remolacha con queso de cabra", description:"Ensalada de remolacha asada con queso de cabra, nueces y rúcula. Colorida y llena de antioxidantes.", mealTime:"comida", category:"ensaladas", prepTime:10, cookTime:45, servings:2, difficulty:"easy", calories:340, protein:12, carbohydrates:28, fat:20, fiber:6, allergens:["lacteos","frutos_secos"], tags:["vegetariano","antioxidantes","sin_gluten"], ingredients:[{name:"Remolacha",quantity:"3 unidades"},{name:"Queso de cabra",quantity:"100g"},{name:"Rúcula",quantity:"60g"},{name:"Nueces",quantity:"30g"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Vinagre balsámico",quantity:"15ml"},{name:"Miel",quantity:"5g"}], instructions:["Envolver la remolacha en papel de aluminio y hornear a 180°C durante 45 minutos.","Pelar y cortar en gajos cuando esté templada.","Montar la ensalada con la rúcula, remolacha, queso de cabra y nueces.","Aliñar con aceite, vinagre balsámico y miel."] },
  { name:"Curry de garbanzos y espinacas", description:"Curry vegano de garbanzos con espinacas, tomate y especias. Plato completo y reconfortante.", mealTime:"comida", category:"vegetariano", prepTime:15, cookTime:25, servings:3, difficulty:"medium", calories:380, protein:16, carbohydrates:52, fat:10, fiber:14, allergens:[], tags:["vegano","sin_gluten","proteina_vegetal","especiado"], ingredients:[{name:"Garbanzos cocidos",quantity:"400g"},{name:"Espinacas",quantity:"200g"},{name:"Tomate triturado",quantity:"300g"},{name:"Leche de coco",quantity:"150ml"},{name:"Cebolla",quantity:"1 unidad"},{name:"Ajo",quantity:"3 dientes"},{name:"Curry en polvo",quantity:"2 cucharaditas"},{name:"Cúrcuma",quantity:"1 cucharadita"},{name:"Jengibre",quantity:"10g"}], instructions:["Sofreír la cebolla, ajo y jengibre en aceite.","Añadir el curry y la cúrcuma. Cocinar 1 minuto.","Incorporar el tomate y cocinar 5 minutos.","Añadir los garbanzos y la leche de coco. Cocinar 15 minutos.","Añadir las espinacas al final y cocinar 2 minutos más.","Servir con arroz integral o pan de pita."] },
  { name:"Ensalada de col rizada con tahini", description:"Kale masajeado con aliño de tahini y limón, con semillas de girasol y arándanos secos.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:0, servings:2, difficulty:"easy", calories:280, protein:10, carbohydrates:24, fat:16, fiber:8, allergens:["sesamo"], tags:["vegano","sin_gluten","superfood","vitaminas"], ingredients:[{name:"Col rizada (kale)",quantity:"150g"},{name:"Tahini",quantity:"30g"},{name:"Limón",quantity:"1 unidad"},{name:"Semillas de girasol",quantity:"20g"},{name:"Arándanos secos",quantity:"20g"},{name:"Ajo",quantity:"1 diente"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Lavar y cortar el kale en trozos, eliminar los tallos duros.","Preparar el aliño mezclando tahini, zumo de limón, ajo y aceite.","Masajear el kale con el aliño durante 2 minutos para ablandarlo.","Añadir las semillas y los arándanos.","Dejar reposar 5 minutos antes de servir."] },
  { name:"Ensalada de sandía con feta y menta", description:"Ensalada refrescante de sandía con queso feta, menta fresca y aceite de oliva. Perfecta para verano.", mealTime:"comida", category:"ensaladas", prepTime:10, cookTime:0, servings:3, difficulty:"easy", calories:180, protein:6, carbohydrates:22, fat:8, fiber:1, allergens:["lacteos"], tags:["vegetariano","sin_gluten","verano","refrescante"], ingredients:[{name:"Sandía",quantity:"500g"},{name:"Queso feta",quantity:"100g"},{name:"Menta fresca",quantity:"15g"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Vinagre balsámico",quantity:"10ml"}], instructions:["Cortar la sandía en cubos o triángulos.","Desmigar el queso feta por encima.","Añadir las hojas de menta.","Aliñar con aceite de oliva y vinagre balsámico."] },
  { name:"Ensalada de lentejas con verduras asadas", description:"Ensalada templada de lentejas con pimiento y calabacín asados, aliñada con vinagreta de mostaza.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:40, servings:3, difficulty:"medium", calories:340, protein:18, carbohydrates:48, fat:8, fiber:14, allergens:[], tags:["vegano","sin_gluten","fibra","hierro"], ingredients:[{name:"Lentejas cocidas",quantity:"300g"},{name:"Pimiento rojo",quantity:"1 unidad"},{name:"Calabacín",quantity:"1 unidad"},{name:"Cebolla roja",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Mostaza de Dijon",quantity:"10g"},{name:"Vinagre de vino",quantity:"15ml"},{name:"Perejil",quantity:"al gusto"}], instructions:["Cortar las verduras en trozos y asar en el horno a 200°C durante 25 minutos.","Mezclar las lentejas con las verduras asadas.","Preparar la vinagreta con aceite, mostaza y vinagre.","Aliñar la ensalada y decorar con perejil."] },
  { name:"Bol de proteína con pollo, arroz y brócoli", description:"Meal prep clásico de fitness: pechuga de pollo, arroz blanco y brócoli al vapor. Simple y efectivo.", mealTime:"comida", category:"fitness", prepTime:10, cookTime:25, servings:2, difficulty:"easy", calories:480, protein:48, carbohydrates:52, fat:8, fiber:6, allergens:[], tags:["alto_proteina","sin_gluten","meal_prep","fitness"], ingredients:[{name:"Pechuga de pollo",quantity:"400g"},{name:"Arroz blanco",quantity:"200g"},{name:"Brócoli",quantity:"300g"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Sal, pimienta y ajo en polvo",quantity:"al gusto"}], instructions:["Cocer el arroz en agua con sal.","Sazonar el pollo y cocinarlo a la plancha 6-7 minutos por cada lado.","Cocer el brócoli al vapor 8 minutos.","Dividir en boles y aliñar con aceite de oliva."] },
  { name:"Atún con arroz integral y aguacate", description:"Bol de atún al natural con arroz integral, aguacate y edamame. Alto en proteína y omega-3.", mealTime:"comida", category:"fitness", prepTime:10, cookTime:20, servings:1, difficulty:"easy", calories:520, protein:38, carbohydrates:48, fat:16, fiber:8, allergens:["pescado","soja"], tags:["alto_proteina","omega3","sin_gluten","meal_prep"], ingredients:[{name:"Atún al natural",quantity:"160g"},{name:"Arroz integral",quantity:"100g"},{name:"Aguacate",quantity:"1/2 unidad"},{name:"Edamame",quantity:"80g"},{name:"Salsa de soja baja en sodio",quantity:"15ml"},{name:"Sésamo",quantity:"5g"}], instructions:["Cocer el arroz integral.","Cocer el edamame al vapor 5 minutos.","Montar el bol con el arroz, atún escurrido, aguacate en láminas y edamame.","Aliñar con salsa de soja y espolvorear sésamo."] },
  { name:"Falafel al horno con salsa de yogur", description:"Falafel de garbanzos horneado (no frito) con salsa de yogur y menta. Más ligero y saludable.", mealTime:"comida", category:"vegetariano", prepTime:20, cookTime:25, servings:3, difficulty:"medium", calories:320, protein:14, carbohydrates:42, fat:10, fiber:10, allergens:["lacteos","sesamo"], tags:["vegetariano","sin_gluten","proteina_vegetal","mediterraneo"], ingredients:[{name:"Garbanzos secos remojados",quantity:"250g"},{name:"Cebolla",quantity:"1/2 unidad"},{name:"Ajo",quantity:"3 dientes"},{name:"Cilantro",quantity:"20g"},{name:"Comino",quantity:"2 cucharaditas"},{name:"Yogur griego",quantity:"150g"},{name:"Menta",quantity:"10g"},{name:"Limón",quantity:"1 unidad"}], instructions:["Precalentar el horno a 200°C.","Triturar los garbanzos con cebolla, ajo, cilantro y comino.","Formar bolas y colocar en bandeja con papel.","Hornear 20-25 minutos dando la vuelta a mitad.","Preparar la salsa mezclando yogur, menta, limón y sal.","Servir los falafel con la salsa."] },
  { name:"Hamburguesa vegana de remolacha y quinoa", description:"Hamburguesa casera de remolacha, quinoa y nueces. Jugosa, colorida y llena de nutrientes.", mealTime:"comida", category:"vegetariano", prepTime:20, cookTime:20, servings:4, difficulty:"medium", calories:280, protein:10, carbohydrates:38, fat:10, fiber:6, allergens:["frutos_secos","gluten"], tags:["vegano","proteina_vegetal","sin_lacteos"], ingredients:[{name:"Remolacha cocida",quantity:"200g"},{name:"Quinoa cocida",quantity:"150g"},{name:"Nueces",quantity:"50g"},{name:"Cebolla",quantity:"1/2 unidad"},{name:"Ajo",quantity:"2 dientes"},{name:"Pan rallado integral",quantity:"40g"},{name:"Comino",quantity:"1 cucharadita"}], instructions:["Triturar la remolacha con las nueces, cebolla y ajo.","Mezclar con la quinoa, pan rallado y comino.","Formar hamburguesas y refrigerar 30 minutos.","Cocinar a la plancha 4-5 minutos por cada lado.","Servir en pan integral con lechuga y tomate."] },
  { name:"Ensalada de quinoa con verduras y limón", description:"Ensalada fría de quinoa con pepino, tomate, cebolla y hierbas. Bajo índice glucémico y completa.", mealTime:"comida", category:"ensaladas", prepTime:15, cookTime:15, servings:3, difficulty:"easy", calories:280, protein:10, carbohydrates:42, fat:8, fiber:5, allergens:[], tags:["vegano","sin_gluten","bajo_ig","proteina_vegetal"], ingredients:[{name:"Quinoa",quantity:"150g"},{name:"Pepino",quantity:"1 unidad"},{name:"Tomate cherry",quantity:"150g"},{name:"Cebolla roja",quantity:"1/4 unidad"},{name:"Perejil",quantity:"20g"},{name:"Menta",quantity:"10g"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Limón",quantity:"1 unidad"}], instructions:["Cocer la quinoa 15 minutos. Enfriar.","Cortar el pepino, tomate y cebolla en dados.","Mezclar con la quinoa, perejil y menta picados.","Aliñar con aceite y zumo de limón."] },
  { name:"Pulpo a la gallega con pimentón", description:"Pulpo cocido con patata, pimentón dulce y aceite de oliva. Plato gallego tradicional y saludable.", mealTime:"comida", category:"mariscos", prepTime:10, cookTime:50, servings:3, difficulty:"medium", calories:280, protein:28, carbohydrates:22, fat:8, fiber:3, allergens:["mariscos"], tags:["sin_gluten","mediterraneo","proteina","tradicional"], ingredients:[{name:"Pulpo cocido",quantity:"600g"},{name:"Patata",quantity:"400g"},{name:"Pimentón dulce",quantity:"2 cucharaditas"},{name:"Aceite de oliva virgen extra",quantity:"40ml"},{name:"Sal gruesa",quantity:"al gusto"}], instructions:["Cocer las patatas con piel en agua con sal.","Pelar y cortar en rodajas.","Cortar el pulpo en rodajas.","Montar en un plato de madera: patatas, pulpo encima.","Espolvorear pimentón, sal gruesa y rociar con aceite de oliva."] },
  { name:"Espaguetis de calabacín con boloñesa de lentejas", description:"Espaguetis de calabacín (zoodles) con salsa boloñesa vegana de lentejas. Sin gluten y bajo en calorías.", mealTime:"comida", category:"vegetariano", prepTime:20, cookTime:30, servings:2, difficulty:"medium", calories:320, protein:18, carbohydrates:38, fat:8, fiber:14, allergens:[], tags:["vegano","sin_gluten","bajo_calorias","fibra"], ingredients:[{name:"Calabacín grande",quantity:"2 unidades"},{name:"Lentejas cocidas",quantity:"200g"},{name:"Tomate triturado",quantity:"300g"},{name:"Cebolla",quantity:"1 unidad"},{name:"Ajo",quantity:"3 dientes"},{name:"Zanahoria",quantity:"1 unidad"},{name:"Orégano y albahaca",quantity:"al gusto"}], instructions:["Hacer los espaguetis de calabacín con un espiralizador.","Sofreír la cebolla, ajo y zanahoria. Añadir el tomate y las lentejas.","Cocinar la salsa 20 minutos con las hierbas.","Saltear los zoodles 2 minutos en una sartén.","Servir los zoodles con la salsa boloñesa."] },
  { name:"Tacos de lechuga con picadillo vegano", description:"Hojas de lechuga rellenas de picadillo de lentejas, aguacate y pico de gallo. Sin gluten.", mealTime:"comida", category:"vegetariano", prepTime:20, cookTime:20, servings:2, difficulty:"medium", calories:300, protein:16, carbohydrates:38, fat:10, fiber:12, allergens:[], tags:["vegano","sin_gluten","mexicano","fibra"], ingredients:[{name:"Lentejas cocidas",quantity:"200g"},{name:"Hojas de lechuga romana",quantity:"8 hojas"},{name:"Aguacate",quantity:"1 unidad"},{name:"Tomate",quantity:"2 unidades"},{name:"Cebolla roja",quantity:"1/4 unidad"},{name:"Cilantro",quantity:"al gusto"},{name:"Limón",quantity:"1 unidad"},{name:"Comino",quantity:"1 cucharadita"}], instructions:["Sazonar las lentejas con comino, sal y pimienta. Saltear 5 minutos.","Preparar el pico de gallo con tomate, cebolla, cilantro y limón.","Machacar el aguacate con sal y limón.","Rellenar las hojas de lechuga con lentejas, guacamole y pico de gallo."] },
  { name:"Pollo con verduras al vapor y arroz integral", description:"Pechuga de pollo al vapor con brócoli, zanahoria y arroz integral. Ideal para control glucémico.", mealTime:"comida", category:"carnes", prepTime:10, cookTime:30, servings:2, difficulty:"easy", calories:420, protein:42, carbohydrates:44, fat:8, fiber:7, allergens:[], tags:["sin_gluten","bajo_ig","alto_proteina","dieta"], ingredients:[{name:"Pechuga de pollo",quantity:"400g"},{name:"Arroz integral",quantity:"150g"},{name:"Brócoli",quantity:"200g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Limón",quantity:"1 unidad"}], instructions:["Cocer el arroz integral.","Cocinar el pollo y las verduras al vapor simultáneamente.","Servir todo junto aliñado con aceite y limón."] },
  { name:"Ensalada antiinflamatoria con cúrcuma", description:"Ensalada de espinacas, zanahoria, nueces y arándanos con aliño de cúrcuma y jengibre.", mealTime:"comida", category:"ensaladas", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:260, protein:7, carbohydrates:22, fat:16, fiber:7, allergens:["frutos_secos"], tags:["vegano","sin_gluten","antiinflamatorio","superfood"], ingredients:[{name:"Espinacas baby",quantity:"100g"},{name:"Zanahoria rallada",quantity:"100g"},{name:"Nueces",quantity:"30g"},{name:"Arándanos frescos",quantity:"50g"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Cúrcuma",quantity:"1/2 cucharadita"},{name:"Jengibre rallado",quantity:"5g"},{name:"Limón",quantity:"1/2 unidad"}], instructions:["Preparar el aliño mezclando aceite, cúrcuma, jengibre y limón.","Mezclar las espinacas con la zanahoria rallada.","Añadir los arándanos y las nueces.","Aliñar y servir."] },
  { name:"Ensalada depurativa de hinojo y naranja", description:"Ensalada fresca de hinojo, naranja, rúcula y aceitunas. Depurativa y digestiva.", mealTime:"comida", category:"ensaladas", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:180, protein:4, carbohydrates:20, fat:9, fiber:5, allergens:[], tags:["vegano","sin_gluten","detox","digestivo","invierno"], ingredients:[{name:"Hinojo",quantity:"1 bulbo"},{name:"Naranja",quantity:"2 unidades"},{name:"Rúcula",quantity:"60g"},{name:"Aceitunas negras",quantity:"30g"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Vinagre de manzana",quantity:"10ml"}], instructions:["Cortar el hinojo en láminas finas.","Pelar las naranjas y cortar en gajos.","Mezclar con la rúcula y las aceitunas.","Aliñar con aceite y vinagre."] },
  { name:"Escalivada con anchoas", description:"Verduras asadas (berenjena, pimiento, cebolla) con anchoas y aceite de oliva. Tapa mediterránea.", mealTime:"comida", category:"vegetariano", prepTime:10, cookTime:50, servings:3, difficulty:"easy", calories:180, protein:8, carbohydrates:18, fat:9, fiber:6, allergens:["pescado"], tags:["sin_gluten","mediterraneo","antioxidantes"], ingredients:[{name:"Berenjena",quantity:"2 unidades"},{name:"Pimiento rojo",quantity:"2 unidades"},{name:"Cebolla",quantity:"1 unidad"},{name:"Anchoas en aceite",quantity:"40g"},{name:"Aceite de oliva virgen extra",quantity:"30ml"},{name:"Ajo",quantity:"2 dientes"}], instructions:["Asar las verduras enteras en el horno a 200°C durante 45 minutos.","Dejar enfriar, pelar y cortar en tiras.","Colocar en un plato y añadir las anchoas.","Aliñar con aceite de oliva y ajo laminado."] },
  { name:"Wrap de lechuga con pollo y aguacate", description:"Hojas de lechuga rellenas de pollo a la plancha, aguacate, tomate y mostaza. Sin carbohidratos.", mealTime:"comida", category:"carnes", prepTime:15, cookTime:15, servings:2, difficulty:"easy", calories:340, protein:36, carbohydrates:10, fat:18, fiber:5, allergens:[], tags:["keto","sin_gluten","alto_proteina","bajo_carbohidratos"], ingredients:[{name:"Pechuga de pollo",quantity:"300g"},{name:"Hojas de lechuga iceberg",quantity:"8 hojas"},{name:"Aguacate",quantity:"1 unidad"},{name:"Tomate cherry",quantity:"80g"},{name:"Mostaza de Dijon",quantity:"15g"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Cocinar el pollo a la plancha y cortar en tiras.","Machacar el aguacate con sal y limón.","Extender la mostaza en las hojas de lechuga.","Rellenar con pollo, aguacate y tomate cherry.","Doblar y servir."] },

  // ═══ MERIENDAS ════════════════════════════════════════════════════════════════
  { name:"Batido verde de espinacas y manzana", description:"Batido verde con espinacas, manzana verde, pepino y jengibre. Detox y lleno de vitaminas.", mealTime:"merienda", category:"batidos", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:130, protein:3, carbohydrates:28, fat:1, fiber:5, allergens:[], tags:["vegano","detox","sin_gluten","vitaminas"], ingredients:[{name:"Espinacas baby",quantity:"40g"},{name:"Manzana verde",quantity:"1 unidad"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Jengibre fresco",quantity:"5g"},{name:"Agua fría",quantity:"200ml"},{name:"Limón",quantity:"unas gotas"}], instructions:["Lavar bien todos los ingredientes.","Añadir a la batidora con el agua fría.","Triturar hasta obtener una textura suave.","Añadir unas gotas de limón y servir inmediatamente."] },
  { name:"Tortitas de arroz con pavo y tomate", description:"Tortas de arroz con lonchas de pavo, tomate y rúcula. Merienda proteica y ligera.", mealTime:"merienda", category:"snacks", prepTime:5, cookTime:0, servings:1, difficulty:"easy", calories:150, protein:12, carbohydrates:18, fat:3, fiber:2, allergens:[], tags:["bajo_calorias","sin_gluten","proteina","rapido"], ingredients:[{name:"Tortas de arroz",quantity:"2 unidades"},{name:"Pechuga de pavo en lonchas",quantity:"60g"},{name:"Tomate",quantity:"1/2 unidad"},{name:"Rúcula",quantity:"20g"}], instructions:["Colocar las lonchas de pavo sobre las tortas de arroz.","Añadir rodajas de tomate y rúcula.","Servir inmediatamente."] },
  { name:"Yogur con granola y plátano", description:"Yogur natural con granola casera sin azúcar y rodajas de plátano. Merienda completa y saciante.", mealTime:"merienda", category:"lacteos", prepTime:3, cookTime:0, servings:1, difficulty:"easy", calories:240, protein:10, carbohydrates:38, fat:6, fiber:4, allergens:["lacteos","gluten","frutos_secos"], tags:["probiotico","energia","fibra"], ingredients:[{name:"Yogur natural sin azúcar",quantity:"150g"},{name:"Granola sin azúcar",quantity:"25g"},{name:"Plátano",quantity:"1/2 unidad"}], instructions:["Verter el yogur en un bol.","Cortar el plátano en rodajas y colocar encima.","Añadir la granola justo antes de comer para que quede crujiente."] },
  { name:"Palitos de zanahoria con guacamole", description:"Bastones de zanahoria cruda con guacamole casero. Snack crujiente y lleno de nutrientes.", mealTime:"merienda", category:"snacks", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:160, protein:3, carbohydrates:18, fat:9, fiber:6, allergens:[], tags:["vegano","sin_gluten","vitaminas","crudo"], ingredients:[{name:"Zanahoria",quantity:"3 unidades"},{name:"Aguacate maduro",quantity:"1 unidad"},{name:"Limón",quantity:"1/2 unidad"},{name:"Cilantro",quantity:"al gusto"},{name:"Sal",quantity:"al gusto"}], instructions:["Pelar y cortar las zanahorias en bastones.","Machacar el aguacate con zumo de limón, cilantro y sal.","Servir los bastones con el guacamole para mojar."] },
  { name:"Golden milk (leche dorada)", description:"Bebida caliente de leche vegetal con cúrcuma, jengibre, canela y pimienta negra. Antiinflamatoria.", mealTime:"merienda", category:"bebidas", prepTime:5, cookTime:5, servings:1, difficulty:"easy", calories:100, protein:3, carbohydrates:12, fat:4, fiber:1, allergens:[], tags:["vegano","sin_gluten","antiinflamatorio","digestivo"], ingredients:[{name:"Leche de avena",quantity:"250ml"},{name:"Cúrcuma",quantity:"1 cucharadita"},{name:"Jengibre en polvo",quantity:"1/4 cucharadita"},{name:"Canela",quantity:"1/4 cucharadita"},{name:"Pimienta negra",quantity:"1 pizca"},{name:"Miel",quantity:"5g"}], instructions:["Calentar la leche de avena sin que llegue a hervir.","Añadir la cúrcuma, jengibre, canela y pimienta.","Batir bien con un batidor de varillas.","Endulzar con miel y servir caliente."] },

  // ═══ CENAS ════════════════════════════════════════════════════════════════════
  { name:"Tortilla española de verduras", description:"Tortilla de patata y verduras con pimiento, cebolla y calabacín. Versión ligera con menos aceite.", mealTime:"cena", category:"huevos", prepTime:20, cookTime:25, servings:3, difficulty:"medium", calories:280, protein:14, carbohydrates:28, fat:12, fiber:4, allergens:["huevos"], tags:["vegetariano","sin_gluten","tradicional"], ingredients:[{name:"Huevos",quantity:"4 unidades"},{name:"Patata",quantity:"300g"},{name:"Cebolla",quantity:"1 unidad"},{name:"Pimiento verde",quantity:"1 unidad"},{name:"Calabacín",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"30ml"},{name:"Sal",quantity:"al gusto"}], instructions:["Pelar y cortar las patatas en rodajas finas. Pochar en aceite con la cebolla.","Añadir el pimiento y calabacín en dados. Cocinar 5 minutos.","Batir los huevos con sal y mezclar con las verduras.","Cuajar la tortilla en una sartén antiadherente a fuego medio-bajo, dando la vuelta a mitad.","Servir templada o fría."] },
  { name:"Crema de brócoli con almendras tostadas", description:"Crema suave de brócoli con caldo de verduras, ajo y almendras tostadas. Cena ligera y nutritiva.", mealTime:"cena", category:"sopas", prepTime:10, cookTime:20, servings:3, difficulty:"easy", calories:200, protein:9, carbohydrates:18, fat:10, fiber:7, allergens:["frutos_secos"], tags:["vegetariano","sin_gluten","bajo_calorias","vitaminas"], ingredients:[{name:"Brócoli",quantity:"600g"},{name:"Caldo de verduras",quantity:"600ml"},{name:"Ajo",quantity:"2 dientes"},{name:"Cebolla",quantity:"1 unidad"},{name:"Almendras laminadas tostadas",quantity:"30g"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Sofreír la cebolla y el ajo en aceite durante 5 minutos.","Añadir el brócoli en ramilletes y el caldo.","Cocinar 15 minutos hasta que el brócoli esté tierno.","Triturar hasta obtener una crema suave.","Servir con las almendras tostadas por encima."] },
  { name:"Revuelto de champiñones y espárragos", description:"Huevos revueltos con champiñones, espárragos trigueros y ajo. Cena proteica y ligera.", mealTime:"cena", category:"huevos", prepTime:10, cookTime:10, servings:2, difficulty:"easy", calories:240, protein:18, carbohydrates:8, fat:14, fiber:4, allergens:["huevos"], tags:["vegetariano","sin_gluten","proteina","rapido"], ingredients:[{name:"Huevos",quantity:"4 unidades"},{name:"Champiñones",quantity:"200g"},{name:"Espárragos trigueros",quantity:"150g"},{name:"Ajo",quantity:"2 dientes"},{name:"Aceite de oliva",quantity:"15ml"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Saltear el ajo laminado en aceite.","Añadir los champiñones laminados y los espárragos troceados.","Cocinar 5 minutos hasta que estén tiernos.","Batir los huevos y añadir a la sartén.","Remover suavemente a fuego bajo hasta que cuajen cremosos."] },
  { name:"Ensalada de aguacate, tomate y mozzarella", description:"Ensalada caprese con aguacate, tomate, mozzarella fresca y albahaca. Cena fresca y nutritiva.", mealTime:"cena", category:"ensaladas", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:380, protein:14, carbohydrates:12, fat:30, fiber:6, allergens:["lacteos"], tags:["vegetariano","sin_gluten","grasas_saludables","italiano"], ingredients:[{name:"Aguacate",quantity:"1 unidad"},{name:"Tomate grande",quantity:"2 unidades"},{name:"Mozzarella fresca",quantity:"125g"},{name:"Albahaca fresca",quantity:"10g"},{name:"Aceite de oliva virgen extra",quantity:"20ml"},{name:"Vinagre balsámico",quantity:"10ml"},{name:"Sal y pimienta",quantity:"al gusto"}], instructions:["Cortar el tomate, aguacate y mozzarella en rodajas.","Montar alternando los ingredientes en un plato.","Añadir las hojas de albahaca.","Aliñar con aceite de oliva, vinagre balsámico, sal y pimienta."] },
  { name:"Sopa de verduras con fideos de arroz", description:"Caldo de verduras con fideos de arroz, zanahoria, apio y espinacas. Cena digestiva y reconfortante.", mealTime:"cena", category:"sopas", prepTime:10, cookTime:20, servings:3, difficulty:"easy", calories:180, protein:6, carbohydrates:32, fat:3, fiber:5, allergens:[], tags:["vegano","sin_gluten","digestivo","bajo_calorias"], ingredients:[{name:"Fideos de arroz",quantity:"100g"},{name:"Zanahoria",quantity:"2 unidades"},{name:"Apio",quantity:"2 tallos"},{name:"Espinacas",quantity:"80g"},{name:"Caldo de verduras",quantity:"1L"},{name:"Ajo",quantity:"2 dientes"},{name:"Jengibre",quantity:"5g"}], instructions:["Calentar el caldo con el ajo y jengibre.","Añadir la zanahoria y el apio en rodajas. Cocinar 10 minutos.","Incorporar los fideos de arroz y cocinar según las instrucciones.","Añadir las espinacas al final y dejar 1 minuto.","Rectificar de sal y servir."] },
  { name:"Pechuga de pollo con salsa de yogur y pepino", description:"Pollo a la plancha con salsa tzatziki de yogur, pepino y eneldo. Cena proteica y refrescante.", mealTime:"cena", category:"carnes", prepTime:15, cookTime:15, servings:2, difficulty:"easy", calories:320, protein:40, carbohydrates:8, fat:12, fiber:2, allergens:["lacteos"], tags:["alto_proteina","sin_gluten","griego","bajo_carbohidratos"], ingredients:[{name:"Pechuga de pollo",quantity:"400g"},{name:"Yogur griego 0%",quantity:"150g"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Eneldo",quantity:"al gusto"},{name:"Ajo",quantity:"1 diente"},{name:"Limón",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Marinar el pollo con limón, aceite, sal y pimienta.","Cocinarlo a la plancha 6-7 minutos por cada lado.","Rallar el pepino y escurrir el exceso de agua.","Mezclar el yogur con el pepino, ajo picado, eneldo y sal.","Servir el pollo con la salsa tzatziki."] },
  { name:"Crema de zanahoria y naranja", description:"Crema suave de zanahoria con zumo de naranja y cúrcuma. Cena ligera, dulce y antiinflamatoria.", mealTime:"cena", category:"sopas", prepTime:10, cookTime:25, servings:3, difficulty:"easy", calories:150, protein:3, carbohydrates:28, fat:4, fiber:5, allergens:[], tags:["vegano","sin_gluten","antiinflamatorio","bajo_calorias"], ingredients:[{name:"Zanahoria",quantity:"600g"},{name:"Naranja",quantity:"1 unidad"},{name:"Cúrcuma",quantity:"1 cucharadita"},{name:"Caldo de verduras",quantity:"600ml"},{name:"Cebolla",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Sofreír la cebolla en aceite hasta transparentar.","Añadir la zanahoria en rodajas, la cúrcuma y el caldo.","Cocinar 20 minutos hasta que la zanahoria esté tierna.","Añadir el zumo de naranja y triturar.","Rectificar de sal y servir."] },
  { name:"Sardinas a la plancha con ensalada verde", description:"Sardinas frescas a la plancha con ensalada de lechuga, pepino y tomate. Cena rica en omega-3.", mealTime:"cena", category:"pescados", prepTime:10, cookTime:8, servings:2, difficulty:"easy", calories:290, protein:28, carbohydrates:10, fat:16, fiber:3, allergens:["pescado"], tags:["omega3","sin_gluten","bajo_carbohidratos","economico"], ingredients:[{name:"Sardinas frescas",quantity:"400g"},{name:"Lechuga",quantity:"100g"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Tomate",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Limón",quantity:"1 unidad"},{name:"Sal",quantity:"al gusto"}], instructions:["Limpiar las sardinas y sazonar con sal.","Cocinarlas a la plancha 3-4 minutos por cada lado.","Preparar la ensalada con lechuga, pepino y tomate.","Aliñar con aceite y limón.","Servir las sardinas sobre la ensalada."] },
  { name:"Pisto manchego con huevo", description:"Pisto de verduras con calabacín, pimiento, tomate y cebolla, coronado con un huevo pochado.", mealTime:"cena", category:"vegetariano", prepTime:15, cookTime:30, servings:2, difficulty:"medium", calories:260, protein:12, carbohydrates:22, fat:14, fiber:7, allergens:["huevos"], tags:["vegetariano","sin_gluten","tradicional","vitaminas"], ingredients:[{name:"Calabacín",quantity:"1 unidad"},{name:"Pimiento rojo",quantity:"1 unidad"},{name:"Pimiento verde",quantity:"1 unidad"},{name:"Tomate",quantity:"3 unidades"},{name:"Cebolla",quantity:"1 unidad"},{name:"Huevos",quantity:"2 unidades"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Ajo",quantity:"2 dientes"}], instructions:["Sofreír la cebolla y el ajo en aceite.","Añadir los pimientos en dados y cocinar 5 minutos.","Incorporar el calabacín y el tomate triturado.","Cocinar a fuego lento 20 minutos.","Hacer un hueco en el pisto y añadir los huevos. Tapar y cocinar 3-4 minutos."] },
  { name:"Ensalada de espinacas con salmón ahumado", description:"Ensalada de espinacas baby con salmón ahumado, alcaparras y vinagreta de mostaza.", mealTime:"cena", category:"ensaladas", prepTime:10, cookTime:0, servings:2, difficulty:"easy", calories:300, protein:22, carbohydrates:8, fat:20, fiber:4, allergens:["pescado"], tags:["omega3","sin_gluten","bajo_carbohidratos","proteina"], ingredients:[{name:"Espinacas baby",quantity:"100g"},{name:"Salmón ahumado",quantity:"150g"},{name:"Alcaparras",quantity:"20g"},{name:"Cebolla roja",quantity:"1/4 unidad"},{name:"Aceite de oliva",quantity:"20ml"},{name:"Mostaza de Dijon",quantity:"5g"},{name:"Vinagre de manzana",quantity:"10ml"},{name:"Limón",quantity:"unas gotas"}], instructions:["Preparar la vinagreta mezclando aceite, mostaza, vinagre y limón.","Colocar las espinacas en un plato.","Añadir el salmón ahumado, las alcaparras y la cebolla roja en aros finos.","Aliñar con la vinagreta y servir."] },
  { name:"Sopa de miso con tofu y algas", description:"Sopa japonesa de miso con tofu sedoso, algas wakame y cebolleta. Probiótica y digestiva.", mealTime:"cena", category:"sopas", prepTime:5, cookTime:10, servings:2, difficulty:"easy", calories:120, protein:8, carbohydrates:10, fat:5, fiber:2, allergens:["soja"], tags:["vegano","sin_gluten","probiotico","asiatico"], ingredients:[{name:"Pasta de miso blanco",quantity:"30g"},{name:"Tofu sedoso",quantity:"150g"},{name:"Algas wakame secas",quantity:"5g"},{name:"Cebolleta",quantity:"2 tallos"},{name:"Agua",quantity:"600ml"}], instructions:["Hidratar las algas wakame en agua fría 5 minutos.","Calentar el agua sin que llegue a hervir.","Disolver la pasta de miso en un poco de agua caliente.","Añadir el tofu en dados, las algas escurridas y el miso.","Servir con la cebolleta picada."] },
  { name:"Crema de guisantes con menta", description:"Crema fría o caliente de guisantes con menta fresca y yogur. Ligera y refrescante.", mealTime:"cena", category:"sopas", prepTime:10, cookTime:15, servings:3, difficulty:"easy", calories:160, protein:8, carbohydrates:22, fat:4, fiber:7, allergens:["lacteos"], tags:["vegetariano","sin_gluten","fibra","verano"], ingredients:[{name:"Guisantes congelados",quantity:"400g"},{name:"Caldo de verduras",quantity:"400ml"},{name:"Menta fresca",quantity:"15g"},{name:"Yogur natural",quantity:"100g"},{name:"Cebolla",quantity:"1 unidad"},{name:"Aceite de oliva",quantity:"15ml"}], instructions:["Sofreír la cebolla en aceite 5 minutos.","Añadir los guisantes y el caldo. Cocinar 10 minutos.","Añadir la menta y triturar.","Incorporar el yogur y mezclar.","Servir fría o templada."] },
  { name:"Sopa de tomate asado con albahaca", description:"Sopa de tomates asados al horno con ajo, cebolla y albahaca fresca. Intensa y aromática.", mealTime:"cena", category:"sopas", prepTime:10, cookTime:45, servings:4, difficulty:"easy", calories:140, protein:4, carbohydrates:20, fat:5, fiber:4, allergens:[], tags:["vegano","sin_gluten","antioxidantes","italiano"], ingredients:[{name:"Tomates",quantity:"1kg"},{name:"Ajo",quantity:"4 dientes"},{name:"Cebolla",quantity:"1 unidad"},{name:"Albahaca fresca",quantity:"20g"},{name:"Aceite de oliva",quantity:"30ml"},{name:"Caldo de verduras",quantity:"400ml"}], instructions:["Cortar los tomates por la mitad y colocar en bandeja con ajo y cebolla.","Rociar con aceite y hornear a 200°C durante 35 minutos.","Triturar las verduras asadas con el caldo.","Añadir la albahaca y triturar de nuevo.","Calentar y rectificar de sal."] },
  { name:"Salmón con costra de hierbas y espárragos", description:"Salmón con costra de hierbas frescas y espárragos a la plancha. Keto y alto en omega-3.", mealTime:"cena", category:"pescados", prepTime:10, cookTime:15, servings:2, difficulty:"easy", calories:420, protein:40, carbohydrates:6, fat:26, fiber:3, allergens:["pescado"], tags:["keto","sin_gluten","omega3","bajo_carbohidratos"], ingredients:[{name:"Salmón en filetes",quantity:"400g"},{name:"Espárragos verdes",quantity:"300g"},{name:"Perejil",quantity:"20g"},{name:"Eneldo",quantity:"10g"},{name:"Ajo",quantity:"2 dientes"},{name:"Aceite de oliva",quantity:"25ml"},{name:"Limón",quantity:"1 unidad"}], instructions:["Mezclar las hierbas picadas con ajo, aceite y ralladura de limón.","Cubrir los filetes de salmón con la mezcla de hierbas.","Hornear a 200°C durante 12-15 minutos.","Asar los espárragos en la plancha con aceite y sal.","Servir con rodajas de limón."] },

  // ═══ POSTRES SALUDABLES ═══════════════════════════════════════════════════════
  { name:"Mousse de chocolate negro y aguacate", description:"Mousse cremoso de chocolate negro con base de aguacate. Sin azúcar refinado, alto en grasas saludables.", mealTime:"cualquiera", category:"postres", prepTime:10, cookTime:0, servings:3, difficulty:"easy", calories:220, protein:4, carbohydrates:18, fat:16, fiber:5, allergens:[], tags:["vegano","sin_gluten","sin_azucar","grasas_saludables"], ingredients:[{name:"Aguacate maduro",quantity:"2 unidades"},{name:"Cacao puro en polvo",quantity:"30g"},{name:"Dátiles",quantity:"6 unidades"},{name:"Leche de coco",quantity:"50ml"},{name:"Vainilla",quantity:"1 cucharadita"}], instructions:["Remojar los dátiles en agua caliente 10 minutos y escurrir.","Triturar el aguacate con los dátiles, cacao, leche de coco y vainilla.","Mezclar hasta obtener una crema completamente suave.","Refrigerar 1 hora antes de servir.","Decorar con cacao en polvo o frutos rojos."] },
  { name:"Helado de plátano con frutos rojos", description:"Helado saludable de plátano congelado con frutos rojos. Sin azúcar añadido, solo 2 ingredientes.", mealTime:"cualquiera", category:"postres", prepTime:5, cookTime:0, servings:2, difficulty:"easy", calories:140, protein:2, carbohydrates:32, fat:1, fiber:4, allergens:[], tags:["vegano","sin_gluten","sin_azucar","2_ingredientes"], ingredients:[{name:"Plátano congelado",quantity:"3 unidades"},{name:"Frutos rojos congelados",quantity:"100g"}], instructions:["Cortar los plátanos en rodajas y congelar al menos 4 horas.","Triturar los plátanos congelados con los frutos rojos en procesador.","Triturar hasta obtener textura cremosa de helado.","Servir inmediatamente o congelar 30 minutos más para textura más firme."] },
  { name:"Compota de manzana con canela", description:"Compota casera de manzana con canela y sin azúcar añadido. Postre digestivo y reconfortante.", mealTime:"cualquiera", category:"postres", prepTime:5, cookTime:20, servings:4, difficulty:"easy", calories:90, protein:1, carbohydrates:22, fat:0, fiber:3, allergens:[], tags:["vegano","sin_gluten","sin_azucar","digestivo"], ingredients:[{name:"Manzanas",quantity:"6 unidades"},{name:"Canela",quantity:"2 cucharaditas"},{name:"Agua",quantity:"100ml"},{name:"Limón",quantity:"unas gotas"}], instructions:["Pelar, descorazonar y cortar las manzanas en trozos.","Cocinar con el agua, canela y limón a fuego medio durante 15-20 minutos.","Triturar parcialmente para obtener la textura deseada.","Servir templada o fría."] },
  { name:"Tarta de queso sin horno con fresas", description:"Cheesecake sin horno con base de dátiles y nueces, relleno de queso fresco y fresas.", mealTime:"cualquiera", category:"postres", prepTime:20, cookTime:0, servings:8, difficulty:"medium", calories:280, protein:8, carbohydrates:24, fat:16, fiber:3, allergens:["lacteos","frutos_secos"], tags:["sin_gluten","sin_horno","fresas"], ingredients:[{name:"Dátiles",quantity:"150g"},{name:"Nueces",quantity:"100g"},{name:"Queso fresco batido",quantity:"400g"},{name:"Yogur griego",quantity:"200g"},{name:"Miel",quantity:"40g"},{name:"Fresas",quantity:"300g"},{name:"Gelatina neutra",quantity:"6g"}], instructions:["Triturar los dátiles y nueces hasta obtener una masa pegajosa. Forrar la base del molde.","Hidratar la gelatina en agua fría.","Mezclar el queso fresco, yogur y miel hasta obtener una crema suave.","Incorporar la gelatina derretida y mezclar.","Verter sobre la base y refrigerar 4 horas.","Decorar con fresas cortadas antes de servir."] },
  { name:"Galletas de avena y plátano", description:"Galletas saludables de avena y plátano sin azúcar añadido. Perfectas para merienda o postre.", mealTime:"cualquiera", category:"postres", prepTime:10, cookTime:15, servings:12, difficulty:"easy", calories:80, protein:2, carbohydrates:14, fat:2, fiber:2, allergens:["gluten"], tags:["vegano","sin_azucar","snack","horneado"], ingredients:[{name:"Copos de avena",quantity:"200g"},{name:"Plátano maduro",quantity:"2 unidades"},{name:"Canela",quantity:"1 cucharadita"},{name:"Pasas",quantity:"30g"}], instructions:["Precalentar el horno a 180°C.","Machacar los plátanos hasta obtener un puré.","Mezclar con la avena, canela y pasas.","Formar pequeñas galletas y colocar en bandeja con papel.","Hornear 12-15 minutos hasta que estén doradas."] },
  { name:"Panna cotta de coco con mango", description:"Panna cotta vegana de leche de coco con coulis de mango. Postre cremoso y tropical.", mealTime:"cualquiera", category:"postres", prepTime:15, cookTime:5, servings:4, difficulty:"medium", calories:200, protein:3, carbohydrates:22, fat:12, fiber:1, allergens:[], tags:["vegano","sin_gluten","tropical","sin_lacteos"], ingredients:[{name:"Leche de coco",quantity:"400ml"},{name:"Mango",quantity:"2 unidades"},{name:"Agar agar",quantity:"4g"},{name:"Miel",quantity:"20g"},{name:"Vainilla",quantity:"1 cucharadita"}], instructions:["Calentar la leche de coco con el agar agar y la miel, removiendo hasta disolver.","Añadir la vainilla y verter en moldes.","Refrigerar 3 horas hasta que cuaje.","Triturar el mango hasta obtener un coulis.","Desmoldar y servir con el coulis de mango."] },

  // ═══ BEBIDAS SALUDABLES ═══════════════════════════════════════════════════════
  { name:"Agua detox de pepino y menta", description:"Agua infusionada con pepino, menta y limón. Hidratante, digestiva y depurativa.", mealTime:"cualquiera", category:"bebidas", prepTime:5, cookTime:0, servings:4, difficulty:"easy", calories:10, protein:0, carbohydrates:2, fat:0, fiber:0, allergens:[], tags:["vegano","sin_gluten","detox","hidratacion"], ingredients:[{name:"Pepino",quantity:"1/2 unidad"},{name:"Menta fresca",quantity:"10g"},{name:"Limón",quantity:"1 unidad"},{name:"Agua fría",quantity:"1L"},{name:"Hielo",quantity:"al gusto"}], instructions:["Cortar el pepino en rodajas y el limón en rodajas.","Añadir al agua junto con las hojas de menta.","Refrigerar 2 horas para que se infusione.","Servir con hielo."] },
  { name:"Zumo verde detox", description:"Zumo de apio, pepino, manzana verde, espinacas y jengibre. Limpieza y energía natural.", mealTime:"desayuno", category:"bebidas", prepTime:10, cookTime:0, servings:1, difficulty:"easy", calories:90, protein:2, carbohydrates:20, fat:1, fiber:3, allergens:[], tags:["vegano","sin_gluten","detox","vitaminas","crudo"], ingredients:[{name:"Apio",quantity:"3 tallos"},{name:"Pepino",quantity:"1/2 unidad"},{name:"Manzana verde",quantity:"1 unidad"},{name:"Espinacas",quantity:"30g"},{name:"Jengibre fresco",quantity:"10g"},{name:"Limón",quantity:"1/2 unidad"}], instructions:["Lavar bien todos los ingredientes.","Pasar por el extractor de zumos.","Beber inmediatamente para conservar los nutrientes."] },
];

async function main() {
  if (!DATABASE_URL) {
    console.error('DATABASE_URL not set');
    process.exit(1);
  }

  const { createConnection } = mysql;
  const conn = await createConnection(DATABASE_URL);
  console.log('Connected to database');

  // Get system user
  const [users] = await conn.execute('SELECT id FROM users LIMIT 1');
  if (users.length === 0) {
    console.error('No users found');
    await conn.end();
    return;
  }
  const systemUserId = users[0].id;
  console.log(`Using userId: ${systemUserId}`);

  let inserted = 0;
  let errors = 0;
  const total = RECIPES.length;

  for (const recipe of RECIPES) {
    try {
      const difficulty = mapDifficulty(recipe.difficulty);
      const ingredients = JSON.stringify(recipe.ingredients || []);
      const instructions = JSON.stringify(recipe.instructions || []);
      const allergens = JSON.stringify(recipe.allergens || []);
      const tags = JSON.stringify(recipe.tags || []);

      await conn.execute(
        `INSERT INTO recipes (
          userId, name, description, mealTime, category,
          preparationTime, cookTime, servings, difficulty,
          caloriesPerServing, proteinsPerServing, carbsPerServing, fatsPerServing, fiberPerServing,
          allergens, tags,
          isPublic, isSeeded, createdAt, updatedAt
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1, NOW(), NOW())`,
        [
          systemUserId,
          recipe.name,
          recipe.description || '',
          recipe.mealTime,
          recipe.category || 'general',
          recipe.prepTime || 10,
          recipe.cookTime || 15,
          recipe.servings || 2,
          difficulty,
          recipe.calories || 300,
          recipe.protein || 15,
          recipe.carbohydrates || 35,
          recipe.fat || 10,
          recipe.fiber || 3,
          allergens,
          tags,
        ]
      );
      inserted++;
      if (inserted % 20 === 0) console.log(`Inserted ${inserted}/${total}...`);
    } catch (e) {
      errors++;
      if (errors <= 5) console.error(`Error inserting "${recipe.name}": ${e.message}`);
    }
  }

  console.log(`\n✓ Done! Inserted: ${inserted}, Errors: ${errors}`);

  const [finalCount] = await conn.execute('SELECT COUNT(*) as count FROM recipes WHERE isSeeded = 1');
  console.log(`Total seeded recipes in DB: ${finalCount[0].count}`);

  const [breakdown] = await conn.execute('SELECT mealTime, COUNT(*) as count FROM recipes WHERE isSeeded = 1 GROUP BY mealTime ORDER BY count DESC');
  for (const row of breakdown) {
    console.log(`  ${row.mealTime}: ${row.count}`);
  }

  await conn.end();
}

main().catch(e => {
  console.error('Fatal error:', e);
  process.exit(1);
});
