ALTER TABLE "recipes" ADD COLUMN "nameEs" varchar(256);--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "nameEn" varchar(256);--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "nameFr" varchar(256);--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "nameIt" varchar(256);--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "namePt" varchar(256);--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "descriptionEs" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "descriptionEn" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "descriptionFr" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "descriptionIt" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "descriptionPt" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "ingredientsJsonEs" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "ingredientsJsonEn" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "ingredientsJsonFr" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "ingredientsJsonIt" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "ingredientsJsonPt" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "instructionsJsonEs" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "instructionsJsonEn" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "instructionsJsonFr" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "instructionsJsonIt" text;--> statement-breakpoint
ALTER TABLE "recipes" ADD COLUMN "instructionsJsonPt" text;