import React, { useMemo } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Calendar, Clock, Download, Trash2 } from "lucide-react";

interface Menu {
  id: number;
  menuName: string;
  menuType: string;
  days: number;
  mealsPerDay: number;
  menuData: string;
  isAutoGenerated: boolean;
  createdAt: Date;
}

interface BuddyKidsMenuViewerProps {
  menus: Menu[];
  onDelete?: (menuId: number) => void;
  isLoading?: boolean;
}

export default function BuddyKidsMenuViewer({ menus, onDelete, isLoading }: BuddyKidsMenuViewerProps) {
  const parsedMenus = useMemo(() => {
    return menus.map((menu) => {
      try {
        const data = typeof menu.menuData === "string" ? JSON.parse(menu.menuData) : menu.menuData;
        return { ...menu, parsedData: data };
      } catch {
        return { ...menu, parsedData: null };
      }
    });
  }, [menus]);

  if (isLoading) {
    return (
      <div className="space-y-4">
        {[1, 2, 3].map((i) => (
          <Card key={i} className="animate-pulse">
            <CardHeader className="pb-3">
              <div className="h-6 bg-gray-200 rounded w-1/3" />
              <div className="h-4 bg-gray-200 rounded w-1/2 mt-2" />
            </CardHeader>
          </Card>
        ))}
      </div>
    );
  }

  if (menus.length === 0) {
    return (
      <Card className="border-dashed">
        <CardContent className="pt-8 pb-8 text-center">
          <Calendar className="w-12 h-12 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500 font-medium">No hay menús generados aún</p>
          <p className="text-sm text-gray-400">Genera un menú automático para comenzar</p>
        </CardContent>
      </Card>
    );
  }

  const mealTypeLabels: Record<string, string> = {
    balanced: "Balanceado",
    high_protein: "Alto en proteína",
    vegetarian: "Vegetariano",
    vegan: "Vegano",
  };

  return (
    <div className="space-y-4">
      {parsedMenus.map((menu) => (
        <Card key={menu.id} className="overflow-hidden hover:shadow-lg transition-shadow">
          <CardHeader className="pb-3 bg-gradient-to-r from-orange-50 to-amber-50">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <CardTitle className="text-lg">{menu.menuName}</CardTitle>
                <CardDescription className="mt-1">
                  {menu.days} días • {menu.mealsPerDay} comidas/día
                </CardDescription>
              </div>
              <div className="flex gap-2">
                {menu.isAutoGenerated && (
                  <Badge variant="secondary" className="bg-orange-100 text-orange-800">
                    IA
                  </Badge>
                )}
                <Badge variant="outline">{mealTypeLabels[menu.menuType] || menu.menuType}</Badge>
              </div>
            </div>
          </CardHeader>

          <CardContent className="pt-4">
            {menu.parsedData?.days ? (
              <div className="space-y-4">
                {menu.parsedData.days.slice(0, 3).map((day: any, idx: number) => (
                  <div key={idx} className="border-l-4 border-orange-300 pl-4 py-2">
                    <h4 className="font-semibold text-sm text-gray-700 mb-2">Día {day.day || idx + 1}</h4>
                    <div className="space-y-1">
                      {day.meals?.slice(0, 3).map((meal: any, mealIdx: number) => (
                        <div key={mealIdx} className="text-sm">
                          <span className="font-medium text-gray-600 capitalize">{meal.type}:</span>
                          <span className="text-gray-700 ml-2">{meal.name}</span>
                        </div>
                      ))}
                      {day.meals?.length > 3 && (
                        <p className="text-xs text-gray-500 italic">+{day.meals.length - 3} más</p>
                      )}
                    </div>
                  </div>
                ))}
                {menu.parsedData.days.length > 3 && (
                  <p className="text-xs text-gray-500 text-center italic">
                    +{menu.parsedData.days.length - 3} días más
                  </p>
                )}
              </div>
            ) : (
              <p className="text-gray-500 text-sm">No se pudo cargar el contenido del menú</p>
            )}

            <div className="flex gap-2 mt-4 pt-4 border-t">
              <Button variant="outline" size="sm" className="flex-1">
                <Download className="w-4 h-4 mr-2" />
                Descargar
              </Button>
              {onDelete && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-red-600 hover:text-red-700 hover:bg-red-50"
                  onClick={() => onDelete(menu.id)}
                >
                  <Trash2 className="w-4 h-4" />
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
